FIELD_HEIGHT = 6

BOTTOM_ROW = FIELD_HEIGHT - 1
FIELD_WIDTH = 7
GO_UP = -1
KEY_TO_QUIT = "x"
MAX_MOVES = FIELD_WIDTH * FIELD_HEIGHT
MIDDLE_COL = FIELD_WIDTH // 2
PLAYER_1_SYMBOL = "X"
PLAYER_2_SYMBOL = "O"
SECOND_FROM_RIGHT = 5
THIRD_FROM_TOP = 2
UNDERLINE_LEN = 21
